### ISSUE TITLE
Missing format error

### ISSUE THREAD

**Issue by tian2992** [msabramo/setuptools-markdown#7]
When running detox I get the following error.

```
File "/tmp/pip-f9No6w-build/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename

    output = pypandoc.convert(markdown_filename, 'rst')

  File "build/bdist.linux-x86_64/egg/pypandoc.py", line 94, in convert

  File "build/bdist.linux-x86_64/egg/pypandoc.py", line 112, in _convert

RuntimeError: Missing format!
```

**Comment by steveYeah** [comment]
I get the same error when trying to install one of my packages from PYPI
```
Downloading rabeye-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_DKtrn/rabeye/setup.py", line 28, in <module>
        setup(**config)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "build/bdist.linux-x86_64/egg/pypandoc.py", line 94, in convert
      File "build/bdist.linux-x86_64/egg/pypandoc.py", line 112, in _convert
    RuntimeError: Missing format!
```

**Comment by marbu** [comment]
This happened to me too when installing `pyp2rpm` into virtualenv. And I guess the the root cause is actully in wrong error handling in `pypandoc` module, see https://github.com/bebraw/pypandoc/issues/86

**Comment by nastevens** [comment]
Digging into this further, it appears that the problem is that (de)tox first creates an sdist, and then installs that sdist into its virtualenv before running the tests. Since `README.md` is not included in the sdist by default, when tox tries to run `setup.py` from the sdist, it can't find the `README.md` file to translate. The error from pypandoc is actually because there's a missing file, but it's being caught as a missing format.

The simplest solution is to add a `MANIFEST.in` file to your project with the following line:

```
include README.md
```

**Comment by hroncok** [comment]
Any news on this?

**Comment by msabramo** [comment]
Thanks, @nastevens!
